<script setup>
import { ref, defineExpose } from 'vue';

const projects = [
    {
        title: 'TheGameCreators CRM Platform',
        description: 'A bespoke CRM platform used by TheGameCreators Ltd to manage their flagship product, the Driving Theory Test 4 in 1 Kit mobile app. Since joining the company, my main focus has been on improving and expanding this system to better support user management, analytics, and administrative workflows.',
        image: 'images/CRM-image.jpg',
        video: '',
        tags: ['PHP', 'Laravel', 'Vue', 'MySQL', 'API Development', 'UI/UX', 'Bootstrap', 'Firebase'],
        highlights: [
            'Built a custom Vue Chart.js component to visualize real-time usage stats from Firebase event data generated by the mobile app.',
            'Integrated admin controls for user management and analytics.',
            'Worked on backend API endpoints and scheduled commands to support new app features and analytics.',
        ],
    },
    {
        title: 'Driving Theory Test 4 in 1 Kit',
        description: "The UK's No. 1 paid iOS and Android app for driving theory test preparation, featuring practice questions, hazard perception clips, and a range of learning tools. I have contributed to both the mobile app and its supporting admin platform, focusing on new features, analytics, and user experience improvements.",
        image: 'images/DTS4in1-image.jpg',
        video: '',
        tags: ['React Native', 'JavaScript', 'Firebase', 'Mobile Development', 'API Development', 'UI/UX'],
        highlights: [
            'Assisted in developing the ghost-hunting Halloween Update, rewarding users with one month in-app subscription.',
            'Contributed to the Leaderboard feature, allowing users to earn points based on specific in-app actions and win weekly prizes.',
            'Enhanced onboarding signup flow and main menu screens for improved user experience.'
        ],
    },
    {
        title: 'CV/Portfolio Site (This Project)',
        description: 'A personal portfolio and CV site built with Vue.js and Tailwind CSS. Features a modern, responsive design, project showcase carousel, and dark mode. Designed to highlight my skills, experience, and recent work in a clean, interactive format.',
        image: 'images/cvProjectSite-image.jpg',
        video: '',
        tags: ['Vue', 'Tailwind', 'Vite', 'Portfolio', 'Frontend'],
        highlights: [
            'Fully responsive, mobile-first design with dark mode support.',
            'Project carousel and interactive timeline components.',
            'Built with Vue 3, Vite, and Tailwind CSS.'
        ],
    },
    {
        title: 'Premier League Tournament Game (WIP)',
        description: 'A full stack web app for hosting friendly Premier League prediction tournaments. Each game week, players pick a team they think will win—earning 3 points for a win, 1 for a draw, and 0 for a loss. The player with the most points at the end wins. Features Normal and Randomised modes. Built with PHP (Laravel), Vue.js, and Tailwind CSS. Currently in development—more features and polish coming soon!',
        image: 'images/PLT-image.png',
        video: '',
        url: 'https://pl-tournament.com',
        status: 'Closed Alpha',
        tags: ['PHP', 'Laravel', 'Vue', 'Tailwind', 'Full Stack'],
        highlights: [
            'Two tournament modes: Normal and Randomised team assignment.',
            'Weekly team picks with 3-1-0 points system and cut-off windows.',
            'User profiles, approvals, and notifications for tournament events.',
        ],
    },
];

const current = ref(0);

function prev() {
    current.value = (current.value - 1 + projects.length) % projects.length;
}
function next() {
    current.value = (current.value + 1) % projects.length;
}

defineExpose({ prev, next });
</script>

<template>
    <div class="relative w-full max-w-3xl mx-auto">
        <div class="flex items-center justify-center">
            <div class="overflow-hidden w-full">
                <div class="flex transition-transform duration-500" :style="{ transform: `translateX(-${current * 100}%)` }">
                    <div v-for="(project, i) in projects" :key="i" class="w-full flex-shrink-0">
                        <div class="overflow-hidden rounded-xl shadow-lg bg-white dark:bg-gray-700">
                            <div class="relative flex items-center justify-center aspect-[16/9] bg-gray-100 dark:bg-gray-700">
                                <img :src="project.image" :alt="project.title" class="w-full h-full object-cover rounded-t-xl" />
                                <span v-if="project.status" class="absolute top-2 right-2 inline-flex items-center gap-1 px-2 py-1 rounded-full text-[10px] sm:text-xs font-semibold bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200 shadow">
                                  {{ project.status }}
                                </span>
                            </div>
                            <div class="p-4 sm:p-6 text-center">
                                <div v-if="project.tags" class="flex flex-wrap justify-center gap-1 sm:gap-2 mb-2 sm:mb-4">
                                    <span v-for="tag in project.tags" :key="tag" class="inline-block bg-blue-100 dark:bg-blue-900 text-blue-700 dark:text-blue-300 px-2 sm:px-3 py-1 rounded-full font-semibold text-xs">
                                        {{ tag }}
                                    </span>
                                </div>
                                <h3 class="text-lg sm:text-xl font-bold mb-1 sm:mb-2">{{ project.title }}
                                  <template v-if="i === 1">
                                    <span class="ml-2 inline-flex gap-2 align-middle">
                                      <a href="https://apps.apple.com/gb/app/driving-theory-test-4-in-1-kit/id829581836" target="_blank" rel="noopener" class="inline-flex items-center gap-1 hover:underline text-gray-700 dark:text-gray-200">
                                        <i class="fab fa-apple text-base sm:text-lg"></i>
                                        <span class="text-xs sm:text-sm">iOS</span>
                                      </a>
                                      <a href="https://play.google.com/store/apps/details?id=uk.co.focusmm.DTSCombo&hl=en_GB" target="_blank" rel="noopener" class="inline-flex items-center gap-1 hover:underline text-gray-700 dark:text-gray-200">
                                        <i class="fab fa-android text-base sm:text-lg text-green-600"></i>
                                        <span class="text-xs sm:text-sm">Android</span>
                                      </a>
                                    </span>
                                  </template>
                                </h3>
                                <p class="text-gray-600 dark:text-gray-300 mb-2 sm:mb-4 text-sm sm:text-base">{{ project.description }}</p>
                                <ul v-if="project.highlights" class="text-left mt-2 sm:mt-4 list-disc list-inside text-gray-700 dark:text-gray-200 text-xs sm:text-base">
                                  <li v-for="(item, j) in project.highlights" :key="j">{{ item }}</li>
                                </ul>
                                <div v-if="project.url" class="mt-3 sm:mt-4">
                                  <a :href="project.url" target="_blank" rel="noopener" class="inline-flex items-center gap-2 px-3 py-2 rounded-md bg-blue-600 text-white hover:bg-blue-700">
                                    <svg class="w-4 h-4" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M13.828 10.172a4 4 0 015.657 5.656l-3.536 3.536a4 4 0 01-5.657-5.656M10 14l4-4m2-2h3a1 1 0 011 1v3"/></svg>
                                    <span>Visit site</span>
                                    <span v-if="project.status" class="text-xs opacity-80">({{ project.status }})</span>
                                  </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Mobile arrows below card -->
        <div class="flex justify-between mt-2 sm:mt-4 md:hidden">
          <button @click="prev" class="p-2 rounded-full bg-gray-100 dark:bg-gray-800 hover:bg-blue-100 dark:hover:bg-blue-900 shadow transition" aria-label="Previous">
            <svg class="w-6 h-6 text-blue-600" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M15 19l-7-7 7-7" /></svg>
          </button>
          <button @click="next" class="p-2 rounded-full bg-gray-100 dark:bg-gray-800 hover:bg-blue-100 dark:hover:bg-blue-900 shadow transition" aria-label="Next">
            <svg class="w-6 h-6 text-blue-600" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M9 5l7 7-7 7" /></svg>
          </button>
        </div>
    </div>
</template> 